services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver_db
    ports:
      - "${MSSQL_PORT}:${MSSQL_PORT}"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: "Express"
    restart: unless-stopped
